//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> Edition { get; set; }
        public string imageurl { get; set; }
        public string notes { get; set; }
        public System.Guid sellerID { get; set; }
        public int bookID { get; set; }
    
        public virtual seller seller { get; set; }
    }
}
