//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seller()
        {
            this.books = new HashSet<book>();
        }
    
        public System.Guid userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int campus { get; set; }
        public int userType { get; set; }
        public string email { get; set; }
        public int prefContact { get; set; }
        public string contactInfo { get; set; }
    
        public virtual campus campu { get; set; }
        public virtual contactmethod contactmethod { get; set; }
        public virtual User User { get; set; }
        public virtual usertype usertype1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book> books { get; set; }
    }
}
