//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class seller_book
    {
        public int sellerbookID { get; set; }
        public int SellerID { get; set; }
        public string BookISBN { get; set; }
        public string Notes { get; set; }
    
        public virtual book book { get; set; }
        public virtual seller seller { get; set; }
    }
}
